version: "3.7"
services:
  db:
    build: db/
    ports: ["8001:5432"]
    
  back:
    build: back/
    ports: ["8080:8080"]
    volumes:
      - ./node:/usr/src/app
    depends_on:
      - "db"
   
  front:
    build: front/
    ports: ["80:80"]