FROM node:14.15-alpine AS build
WORKDIR /usr/src/app
COPY lottoFront/package.json package-lock.json ./
RUN npm install
COPY lottoFront/ .
RUN npm run build

FROM nginx:1.17.1-alpine
#COPY nginx.conf /etc/nginx/nginx.conf
COPY --from=build /usr/src/app/dist/lottoFront /usr/share/nginx/html